# Turns a bootc desktop image into a live environment that can install that same image.
# The result is meant to be converted to an ISO with `image-builder build bootc-generic-iso`,
# see https://osbuild.org/docs/developer-guide/projects/image-builder/advanced/bootc/isos/
#
# Build with --cap-add sys_admin --security-opt label=disable

# The image to install, as it will be referenced from the installer
ARG IMAGE_REF
# The image to build the live environment from, if it can't be referenced like the one to install
ARG BASE_IMAGE=${IMAGE_REF}
FROM ${BASE_IMAGE}

ARG IMAGE_REF
# The image the installed system gets its updates from, IMAGE_REF if empty
ARG UPDATE_IMAGE_REF
# Name shown in the boot menu
ARG ISO_NAME
# Volume label of the ISO, derived from ISO_NAME if empty
ARG ISO_LABEL

RUN --mount=type=bind,source=.,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh
