---
name: SBOM Generation

inputs:
  image-ref:
    description: The reference to the image for which the SBOM will be generated
    required: true

outputs:
  sbom-path:
    description: The path to the generated SBOM file
    value: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}

runs:
  using: "composite"
  steps:
    # SBOM generation is pretty heavy, make some room
    - name: Maximize build space
      uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
      with:
        remove-codeql: true

    - name: Setup Syft
      id: setup-syft
      uses: anchore/sbom-action/download-syft@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0

    - name: Generate SBOM
      id: generate-sbom
      env:
        SYFT_CMD: ${{ steps.setup-syft.outputs.cmd }}
      shell: bash
      run: |
        OUTPUT_PATH="$(mktemp -d)/sbom.json"
        export SYFT_PARALLELISM=$(($(nproc)*2))
        $SYFT_CMD ${{ inputs.image-ref }} --select-catalogers "rpm,+sbom-cataloger" -o spdx-json=${OUTPUT_PATH}
        echo "OUTPUT_PATH=${OUTPUT_PATH}" >> $GITHUB_OUTPUT
