---
name: SBOM Generation

inputs:
  image-ref:
    description: The reference to the image for which the SBOM will be generated
    required: true
  artifact-name:
    description: The name to use for the uploaded SBOM artifact (without extension)
    required: false
    default: sbom

outputs:
  sbom-path:
    description: The path to the generated SBOM file
    value: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}
  artifact-name:
    description: The name of the uploaded SBOM artifact (with extension)
    value: ${{ steps.generate-sbom.outputs.ARTIFACT_NAME }}

runs:
  using: "composite"
  steps:
    # SBOM generation is pretty heavy, make some room
    - name: Maximize build space
      uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6 # v10 when it gets tagged
      with:
        extra-squeeze: false

    # Add a swapfile to help with memory-intensive SBOM generation
    # Copied from https://github.com/m2Giles/m2os/blob/3c7bd6faf6637dd99d6d34ffd177859e23c0945f/.github/workflows/gen-sbom.yml#L73-L99
    - name: Setup
      id: mkswap
      shell: bash
      run: |
        set -eou pipefail
        echo "=== FREE SPACE ==="
        df -h
        echo "=== MEMORY AND SWAP ==="
        free -h
        swapon --show
        echo "=== MAKING SWAPFILE ==="
        SWAPS=$(grep -v Filename /proc/swaps | awk '{print $1}' || true)
        sudo swapoff -a
        for SWAP in $SWAPS; do
            sudo rm -f "$SWAP"
        done
        SWAP_FILE="/mnt/swapfile"
        SWAP_FILE_2="/swapfile"
        sudo fallocate -l 70G "$SWAP_FILE"
        sudo fallocate -l 16G "$SWAP_FILE_2"
        sudo chmod 600 "$SWAP_FILE"
        sudo chmod 600 "$SWAP_FILE_2"
        sudo mkswap "$SWAP_FILE"
        sudo mkswap "$SWAP_FILE_2"
        sudo swapon "$SWAP_FILE"
        sudo swapon "$SWAP_FILE_2"
        echo "=== FREE SPACE ==="
        df -h
        echo "=== MEMORY AND SWAP ==="
        free -h
        swapon --show

    - name: Setup Syft
      id: setup-syft
      uses: anchore/sbom-action/download-syft@0b82b0b1a22399a1c542d4d656f70cd903571b5c # v0

    - name: Generate SBOM
      id: generate-sbom
      env:
        SYFT_CMD: ${{ steps.setup-syft.outputs.cmd }}
      shell: bash
      run: |
        NAME=${{ inputs.artifact-name }}
        # Remove consecutive dashes (when there's no variant, for example)
        NAME=${NAME//--/-}
        # Set ARTIFACT_NAME for use in artifact upload (replace / with _)
        echo "ARTIFACT_NAME=${NAME//\//_}.spdx.json" >> "$GITHUB_OUTPUT"

        OUTPUT_PATH="$(mktemp -d)/${NAME//\//_}.spdx.json"
        export SYFT_PARALLELISM=$(($(nproc)*2))
        $SYFT_CMD ${{ inputs.image-ref }} --select-catalogers "rpm,+sbom-cataloger" -o spdx-json=${OUTPUT_PATH}
        echo "OUTPUT_PATH=${OUTPUT_PATH}" >> $GITHUB_OUTPUT

    - name: Upload SBOM to Job Artifacts
      id: upload-sbom
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
      with:
        name: ${{ steps.generate-sbom.outputs.ARTIFACT_NAME }}
        path: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}
        if-no-files-found: error
        compression-level: 9
