---
name: SBOM Generation

inputs:
  image-ref:
    description: The reference to the image for which the SBOM will be generated
    required: true

outputs:
  sbom-path:
    description: The path to the generated SBOM file
    value: ${{ steps.generate-sbom.outputs.OUTPUT_PATH }}

runs:
  using: "composite"
  steps:
    - name: Setup Syft
      id: setup-syft
      uses: anchore/sbom-action/download-syft@da167eac915b4e86f08b264dbdbc867b61be6f0c # v0

    - name: Generate SBOM
      id: generate-sbom
      env:
        SYFT_CMD: ${{ steps.setup-syft.outputs.cmd }}
      shell: bash
      run: |
        sudo systemctl start podman.socket

        OUTPUT_PATH="$(mktemp -d)/sbom.json"
        export SYFT_PARALLELISM=$(($(nproc)*2))
        sudo $SYFT_CMD ${{ inputs.image-ref }} -o spdx-json=${OUTPUT_PATH}
        echo "OUTPUT_PATH=${OUTPUT_PATH}" >> $GITHUB_OUTPUT
