---
name: Upload to Amazon S3

inputs:
  directory:
    description: "The directory containing the files to upload"
    required: true
  bucket:
    description: "The Amazon S3 bucket to upload the files to"
    required: true
  path:
    description: "The path to the files to upload, relative to the bucket root"
    required: true
    default: ""
  aws-default-region:
    description: "The AWS region to use for S3 uploads"
    required: true
  AWS_ROLE_ARN:
    description: "The AWS role ARN to assume for S3 uploads"
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      if: ${{ inputs.AWS_ROLE_ARN != '' && inputs.aws-default-region != '' }}
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        role-session-name: almalinux-bootc-s3-${{ github.run_id }}
        aws-region: ${{ inputs.aws-default-region }}
        role-duration-seconds: 900  # 15 minutes, the minimum

    - name: Upload to S3
      id: upload-s3
      env:
        BUCKET: ${{ inputs.bucket }}
      shell: bash
      run: |-
        # Upload the files to S3 bucket
        aws s3 cp ${{ inputs.directory }} \
            s3://${BUCKET}/${{ inputs.path }}/ \
            --recursive --acl public-read
