---
name: Build bootable artifacts

inputs:
  platform:
    description: The platform to build the image for (e.g., "x86_64", "arm64")
    required: true
  image:
    description: Full podman image reference, including hash (e.g., "registry.example.com/image@sha256")
    required: true
  image-name:
    description: Name of the image, will be used to name the artifact files (e.g., "my-image")
    required: true
  image-types:
    description: The types of bootable artifacts to build (e.g., "iso,raw")
    required: false
    default: "iso"
  update_is_signed:
    description: Whether the image is signed or not
    required: false
  update_origin_ref:
    description: Image reference to update from (e.g., "{image}:latest")
    required: true
  config-file:
    description: Path to the bootable artifacts configuration file
    required: true
  use-librepo:
    description: "Use librepo to download the image"
    required: false
  additional-args:
    description: "Additional arguments to pass to the bootc-image-builder"
    required: false
  REGISTRY:
    description: The container registry URL (e.g., "registry.example.com")
    required: true
  REGISTRY_USER:
    description: The username for the container registry login
    required: true
  REGISTRY_TOKEN:
    description: The token for authenticating with the container registry
    required: true

outputs:
  output_directory:
    description: The directory where the built artifacts and checksums are stored
    value: ${{ steps.rename.outputs.output_directory }}
  artifact_basename:
    description: The base name of the artifacts
    value: ${{ steps.rename.outputs.artifact_basename }}

runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.REGISTRY_USER }}
        password: ${{ inputs.REGISTRY_TOKEN }}

    - name: Set up environment
      id: set-env
      shell: bash
      run: |
        ARCH=${{ inputs.platform }}
        echo "CLEAN_ARCH=${ARCH//\//_}" >> "$GITHUB_ENV"

    - name: Prepare bootable artifacts configuration
      shell: bash
      run: |
        [ "${{ inputs.update_is_signed }}" = "true" ] && SIG="--enforce-container-sigpolicy"

        sed -i 's#<UPDATE_IMAGE_REF>#${{ inputs.update_origin_ref }}#g' ${{ inputs.config-file }}
        sed -i "s#<IMAGE_SIGNED>#${SIG}#g" ${{ inputs.config-file }}
        cat ${{ inputs.config-file }}

        [ "${{ inputs.use-librepo }}" = "true" ] && USE_LIBREPO="True" || USE_LIBREPO="False"
        ADDITIONAL_ARGS="--target-arch=${{ env.CLEAN_ARCH }} --use-librepo=${USE_LIBREPO} ${{ inputs.additional-args }}"

        echo "ADDITIONAL_ARGS=${ADDITIONAL_ARGS}" >> "$GITHUB_ENV"

    - name: Build bootable artifacts
      id: build
      uses: osbuild/bootc-image-builder-action@4503a3445240ffc85cccf8f57d7cab5634e351e2
      with:
        config-file: ${{ inputs.config-file }}
        image: ${{ inputs.image }}
        additional-args: ${{ env.ADDITIONAL_ARGS }}
        types: ${{ inputs.image-types }}

    - name: Rename bootable artifacts
      id: rename
      env:
        OUTPUT_PATH: output-${{ env.CLEAN_ARCH }}
      shell: bash
      run: |
        set -x
        mkdir -p ${{ env.OUTPUT_PATH }}
        OUTPUT_DIRECTORY="$(realpath ${{ env.OUTPUT_PATH }})"
        ARTIFACT_BASENAME="${{ inputs.image-name }}-${{ env.CLEAN_ARCH }}"

        echo '${{ steps.build.outputs.output-paths }}' | jq -c '.[]' | while read -r artifact; do
          ARTIFACT_PATH=$(echo "$artifact" | jq -r '.path')
          ARTIFACT_CHECKSUM=$(echo "$artifact" | jq -r '.checksum')
          ARTIFACT_EXTENSION=$(echo "$ARTIFACT_PATH" | awk -F. '{print $NF}')

          ARTIFACT_NAME="${ARTIFACT_BASENAME}.${ARTIFACT_EXTENSION}"
          CHECKSUM_NAME="${ARTIFACT_NAME}-CHECKSUM"

          cp "$ARTIFACT_PATH" "${OUTPUT_DIRECTORY}/${ARTIFACT_NAME}"
          echo "$ARTIFACT_CHECKSUM" > "${OUTPUT_DIRECTORY}/${CHECKSUM_NAME}"
        done

        echo "output_directory=${OUTPUT_DIRECTORY}" >> "${GITHUB_OUTPUT}"
        echo "artifact_basename=${ARTIFACT_BASENAME}" >> "${GITHUB_OUTPUT}"
