name: Build ISO
on:
  workflow_call:
    inputs:
      image:
        description: "Full podman image reference, including hash"
        required: true
        type: string
      image-name:
        description: "Name of the image, will be used to name the file name ISO"
        required: true
        type: string
      update_origin_ref:
        description: "Image reference to update from (ie: {image}:latest)"
        required: false
        type: string
      update_is_signed:
        description: "Whether the image is signed or not"
        required: false
        type: boolean
        default: true
      config-file:
        description: "Path to the ISO configuration file"
        required: true
        type: string
      platforms:
        description: "The platforms to build the image for"
        required: false
        type: string
        default: "amd64,arm64"
      use_librepo:
        description: "Use librepo to download the image"
        required: false
        type: boolean
        default: false
      REGISTRY_USER:
        description: "The username to use for the registry"
        required: false
        type: string
        default: "${{ github.actor }}"
      REGISTRY:
        description: "The registry to push the image to"
        required: false
        type: string
        default: "ghcr.io"
      upload-to-github:
        description: "Upload the ISO to GitHub Actions artifacts"
        required: false
        type: boolean
        default: true
      upload-to-cloudflare:
        description: "Upload the ISO to Cloudflare"
        required: false
        type: boolean
        default: false
      upload-to-s3:
        description: "Upload the ISO to S3"
        required: false
        type: boolean
        default: false
      bucket:
        description: "The S3/R2 bucket to upload the ISO to"
        required: false
        type: string
      aws-default-region:
        description: "The AWS region to use for S3 uploads"
        required: false
        type: string
    secrets:
      REGISTRY_TOKEN:
        description: "The token to use for the registry"
        required: true
      R2_ACCOUNT_ID:
        description: "Cloudflare R2 account ID"
        required: false
      ACCESS_KEY_ID:
        description: "S3/R2 access key ID"
        required: false
      SECRET_ACCESS_KEY:
        description: "S3/R2 secret access key"
        required: false

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          # turn the comma separated string into a list
          platforms=()
          IFS=',' read -r -a platforms <<< "${{ inputs.platforms }}"

          MATRIX="{\"include\":[]}"
          for platform in "${platforms[@]}"; do
            MATRIX=$(echo $MATRIX | jq ".include += [{\"platform\": \"$platform\"}]")
          done
          echo "matrix=$(echo $MATRIX | jq -c '.')" >> $GITHUB_OUTPUT

  build-iso:
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Login to Container Registry
        run: |
          echo ${{ secrets.REGISTRY_TOKEN }} | podman login -u ${{ inputs.REGISTRY_USER }} --password-stdin ${{ inputs.REGISTRY }}

      - name: Set up environment
        id: set-env
        run: |
          ARCH=${{ matrix.platform }}
          echo "CLEAN_ARCH=${ARCH//\//_}" >> "$GITHUB_ENV"

      - name: Prepare ISO configuration
        shell: bash
        run: |
          [ "${{ inputs.update_is_signed }}" = "true" ] && SIG="--enforce-container-sigpolicy"

          sed -i 's#<UPDATE_IMAGE_REF>#${{ inputs.update_origin_ref }}#g' ${{ inputs.config-file }}
          sed -i "s#<IMAGE_SIGNED>#${SIG}#g" ${{ inputs.config-file }}
          cat ${{ inputs.config-file }}

      - name: Build ISO
        id: build
        #uses: ublue-os/bootc-image-builder-action@b98784c42327746e107a6a753b64f44823bdbf2f
        uses: alexiri/bootc-image-builder-action@platform
        with:
          image: ${{ inputs.image }}
          type: iso
          use-librepo: ${{ inputs.use_librepo }}
          config-file: ${{ inputs.config-file }}
          platform: linux/${{ matrix.platform }}

      - name: Rename ISO
        id: rename
        env:
          IMAGE_NAME: ${{ inputs.image-name }}-${{ env.CLEAN_ARCH }}-live.iso
          OUTPUT_PATH: output-${{ env.CLEAN_ARCH }}
        run: |
          set -x
          mkdir -p ${{ env.OUTPUT_PATH }}
          OUTPUT_DIRECTORY="$(realpath ${{ env.OUTPUT_PATH }})"

          mv ${{ steps.build.outputs.output-path }} "${OUTPUT_DIRECTORY}/${IMAGE_NAME}"
          mv ${{ steps.build.outputs.checksum-path }} "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-CHECKSUM"

          echo "output_directory=$OUTPUT_DIRECTORY" >> "${GITHUB_OUTPUT}"

      - name: Upload ISOs and Checksum to Job Artifacts
        if: inputs.upload-to-github == true
        id: upload-gh
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.image-name }}-${{ env.CLEAN_ARCH }}-live
          path: ${{ steps.rename.outputs.output_directory }}
          if-no-files-found: error
          compression-level: 0
          overwrite: true
          retention-days: 7

      - name: Summary
        if: inputs.upload-to-github == true
        run: |
          echo "Artifact URL: ${{ steps.upload-gh.outputs.artifact-url }}" >> $GITHUB_STEP_SUMMARY
          echo "Digest: ${{ steps.upload-gh.outputs.artifact-digest }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload to Cloudflare
        if: inputs.upload-to-cloudflare == true
        id: upload-cf
        uses: ryand56/r2-upload-action@3bee737337fc7ecb450bedfff45cfa2ed953e576 # v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          r2-bucket: ${{ inputs.bucket }}
          source-dir: ${{ steps.rename.outputs.output_directory }}
          destination-dir: ./

      - name: Upload to S3
        if: inputs.upload-to-s3 == true
        id: upload-s3
        env:
          IMAGE_NAME: ${{ inputs.image-name }}-${{ env.CLEAN_ARCH }}-live.iso
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-default-region }}
          BUCKET: ${{ inputs.bucket }}
        run: |-
          # Upload the files to S3 bucket
          aws s3 cp ${{ steps.rename.outputs.output_directory }} \
              s3://${BUCKET}/${{ inputs.image-name }}/ \
              --recursive

           # Make them uploaded file publicly available
          aws s3api put-object-tagging \
              --bucket ${BUCKET} \
              --key ${{ inputs.image-name }}/${IMAGE_NAME} \
              --tagging 'TagSet={Key=public,Value=yes}'

          aws s3api put-object-tagging \
              --bucket ${BUCKET} \
              --key ${{ inputs.image-name }}/${IMAGE_NAME}-CHECKSUM \
              --tagging 'TagSet={Key=public,Value=yes}'

          echo "ISO: https://${BUCKET}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/${{ inputs.image-name }}/${IMAGE_NAME}" >> $GITHUB_STEP_SUMMARY
          echo "Digest: https://${BUCKET}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/${{ inputs.image-name }}/${IMAGE_NAME}-CHECKSUM" >> $GITHUB_STEP_SUMMARY
