name: Build ISO
on:
  workflow_call:
    inputs:
      image:
        description: "Full podman image reference, including hash"
        required: true
        type: string
      image-name:
        description: "Name of the image, will be used to name the file name ISO"
        required: true
        type: string
      update-origin-ref:
        description: "Image reference to update from (ie: {image}:latest)"
        required: false
        type: string
      hook-script:
        description: "Path to a script that runs at the end of the live image build, to customize the live environment or the installer"
        required: false
        type: string
      skip-maximize-build-space:
        description: "Skip maximizing build space"
        required: false
        type: boolean
        default: false
      platforms:
        description: "The platforms to build ISOs for, any of amd64 and arm64"
        required: false
        type: string
        default: "amd64,arm64"
      REGISTRY_USER:
        description: "The username to use for the registry"
        required: false
        type: string
        default: "${{ github.actor }}"
      REGISTRY:
        description: "The registry to push the image to"
        required: false
        type: string
        default: "ghcr.io"
      upload-to-github:
        description: "Upload the ISO to GitHub Actions artifacts"
        required: false
        type: boolean
        default: true
      upload-to-cloudflare:
        description: "Upload the ISO to Cloudflare"
        required: false
        type: boolean
        default: false
      upload-to-s3:
        description: "Upload the ISO to S3"
        required: false
        type: boolean
        default: false
      s3-path:
        description: "The path to upload the ISO to in S3"
        required: false
        type: string
      bucket:
        description: "The S3/R2 bucket to upload the ISO to"
        required: false
        type: string
      aws-default-region:
        description: "The AWS region to use for S3 uploads"
        required: false
        type: string
    secrets:
      REGISTRY_TOKEN:
        description: "The token to use for the registry"
        required: true
      R2_ACCOUNT_ID:
        description: "Cloudflare R2 account ID"
        required: false
      ACCESS_KEY_ID:
        description: "Cloudflare R2 access key ID"
        required: false
      SECRET_ACCESS_KEY:
        description: "Cloudflare R2 secret access key"
        required: false
      AWS_ROLE_ARN:
        description: "The AWS role ARN to assume for AWS S3 uploads"
        required: false

env:
  INTERNAL_ACTIONS_REF: v12.1

jobs:
  generate_matrix:
    runs-on: ubuntu-26.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        env:
          PLATFORMS: ${{ inputs.platforms }}
        run: |
          # Turn the comma separated string into a matrix
          echo "matrix=$(jq -cn --arg platforms "${PLATFORMS}" '{include: ($platforms | split(",") | map({platform: .}))}')" >> $GITHUB_OUTPUT

  build-iso:
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-26.04-arm' || 'ubuntu-26.04' }}
    timeout-minutes: 60
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    permissions:
      id-token: write # For uploads to AWS S3
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout github actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: AlmaLinux/atomic-ci
          ref: ${{ env.INTERNAL_ACTIONS_REF }}
          path: github-actions

      - name: Build ISO
        id: build-iso
        uses: ./github-actions/.github/actions/build-iso
        with:
          image: ${{ inputs.image }}
          image-name: ${{ inputs.image-name }}
          update-origin-ref: ${{ inputs.update-origin-ref }}
          hook-script: ${{ inputs.hook-script }}
          skip-maximize-build-space: ${{ inputs.skip-maximize-build-space }}
          platform: ${{ matrix.platform }}
          REGISTRY: ${{ inputs.REGISTRY }}
          REGISTRY_USER: ${{ inputs.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Upload to Job Artifacts
        if: inputs.upload-to-github == true
        uses: ./github-actions/.github/actions/upload-gh
        with:
          artifact-name: ${{ steps.build-iso.outputs.artifact-name }}
          directory: ${{ steps.build-iso.outputs.output-directory }}

      - name: Upload to Cloudflare
        if: inputs.upload-to-cloudflare == true
        uses: ./github-actions/.github/actions/upload-r2
        with:
          directory: ${{ steps.build-iso.outputs.output-directory }}
          bucket: ${{ inputs.bucket }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Upload to AWS S3
        if: inputs.upload-to-s3 == true
        uses: ./github-actions/.github/actions/upload-s3
        with:
          directory: ${{ steps.build-iso.outputs.output-directory }}
          bucket: ${{ inputs.bucket }}
          path: ${{ inputs.s3-path }}
          aws-default-region: ${{ inputs.aws-default-region }}
          iso-name: ${{ steps.build-iso.outputs.iso-name }}
          checksum-name: ${{ steps.build-iso.outputs.checksum-name }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
