name: Build bootable artifacts
on:
  workflow_call:
    inputs:
      image:
        description: "Full podman image reference, including hash"
        required: true
        type: string
      image-name:
        description: "Name of the image, will be used to name the artifact files"
        required: true
        type: string
      image-types:
        description: "The types of bootable artifacts to build (ie: iso,raw)"
        required: false
        type: string
        default: "iso"
      update_origin_ref:
        description: "Image reference to update from (ie: {image}:latest)"
        required: false
        type: string
      update_is_signed:
        description: "Whether the image is signed or not"
        required: false
        type: boolean
        default: true
      config-file:
        description: "Path to the bootable artifacts configuration file"
        required: true
        type: string
      platforms:
        description: "The platforms to build the image for"
        required: false
        type: string
        default: "amd64,arm64"
      use-librepo:
        description: "Use librepo to download the image"
        required: false
        type: boolean
        default: false
      additional-args:
        description: "Additional arguments to pass to the bootc-image-builder"
        required: false
        type: string
      REGISTRY_USER:
        description: "The username to use for the registry"
        required: false
        type: string
        default: "${{ github.actor }}"
      REGISTRY:
        description: "The registry to push the image to"
        required: false
        type: string
        default: "ghcr.io"
      upload-to-github:
        description: "Upload the artifacts to GitHub Actions artifacts"
        required: false
        type: boolean
        default: true
      upload-to-cloudflare:
        description: "Upload the artifacts to Cloudflare"
        required: false
        type: boolean
        default: false
      upload-to-s3:
        description: "Upload the artifacts to S3"
        required: false
        type: boolean
        default: false
      bucket:
        description: "The S3/R2 bucket to upload the artifacts to"
        required: false
        type: string
      path:
        description: "The path to upload the artifacts to in S3/R2"
        required: false
        type: string
      aws-default-region:
        description: "The AWS region to use for S3 uploads"
        required: false
        type: string
      INTERNAL_ACTIONS_REPO:
        description: "The repository that contains the internal actions used in this workflow"
        required: false
        type: string
        default: AlmaLinux/atomic-ci
      INTERNAL_ACTIONS_REF:
        description: "The ref to use for the internal actions repository"
        required: false
        type: string
        default: v11
    secrets:
      REGISTRY_TOKEN:
        description: "The token to use for the registry"
        required: true
      R2_ACCOUNT_ID:
        description: "Cloudflare R2 account ID"
        required: false
      ACCESS_KEY_ID:
        description: "Cloudflare R2 access key ID"
        required: false
      SECRET_ACCESS_KEY:
        description: "Cloudflare R2 secret access key"
        required: false
      AWS_ROLE_ARN:
        description: "The AWS role ARN to assume for AWS S3 uploads"
        required: false

env:
  INTERNAL_ACTIONS_REPO: ${{ inputs.INTERNAL_ACTIONS_REPO }}
  INTERNAL_ACTIONS_REF: ${{ inputs.INTERNAL_ACTIONS_REF }}

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          # turn the comma separated string into a list
          platforms=()
          IFS=',' read -r -a platforms <<< "${{ inputs.platforms }}"

          MATRIX="{\"include\":[]}"
          for platform in "${platforms[@]}"; do
            MATRIX=$(echo $MATRIX | jq ".include += [{\"platform\": \"$platform\"}]")
          done
          echo "matrix=$(echo $MATRIX | jq -c '.')" >> $GITHUB_OUTPUT

  build-bootable-artifacts:
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Checkout github actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          repository: ${{ env.INTERNAL_ACTIONS_REPO }}
          ref: ${{ env.INTERNAL_ACTIONS_REF }}
          path: github-actions

      - name: Build bootable artifacts
        id: build-bootable-artifacts
        uses: ./github-actions/.github/actions/build-bootable-artifacts
        with:
          image: ${{ inputs.image }}
          image-name: ${{ inputs.image-name }}
          image-types: ${{ inputs.image-types }}
          update_origin_ref: ${{ inputs.update_origin_ref }}
          update_is_signed: ${{ inputs.update_is_signed }}
          config-file: ${{ inputs.config-file }}
          platform: ${{ matrix.platform }}
          use-librepo: ${{ inputs.use-librepo }}
          additional-args: ${{ inputs.additional-args }}
          REGISTRY: ${{ inputs.REGISTRY }}
          REGISTRY_USER: ${{ inputs.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

      - name: Upload to Job Artifacts
        if: inputs.upload-to-github == true
        uses: ./github-actions/.github/actions/upload-gh
        with:
          artifact_basename: ${{ steps.build-bootable-artifacts.outputs.artifact_basename }}
          directory: ${{ steps.build-bootable-artifacts.outputs.output_directory }}

      - name: Upload to Cloudflare
        if: inputs.upload-to-cloudflare == true
        uses: ./github-actions/.github/actions/upload-r2
        with:
          directory: ${{ steps.build-bootable-artifacts.outputs.output_directory }}
          bucket: ${{ inputs.bucket }}
          path: ${{ inputs.path }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Upload to AWS S3
        if: inputs.upload-to-s3 == true
        uses: ./github-actions/.github/actions/upload-s3
        with:
          directory: ${{ steps.build-bootable-artifacts.outputs.output_directory }}
          bucket: ${{ inputs.bucket }}
          path: ${{ inputs.path }}
          aws-default-region: ${{ inputs.aws-default-region }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
