name: Create release
on:
  workflow_call:
    inputs:
      image-name:
        description: "The name of the image"
        required: true
        type: string
      version:
        description: "The version of the image"
        required: true
        type: string
      latest-image-ref:
        description: "The latest image reference"
        required: true
        type: string
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-26.04

    steps:
      - name: Fetch Changelogs
        id: download-changelogs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: changelog-${{ inputs.image-name }}-*
          merge-multiple: true
          path: /tmp/changelogs

      - name: Fetch SBOMs
        id: download-sbom
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: "*.spdx.json"
          merge-multiple: true
          path: /tmp/sboms

      - name: Compress SBOMs
        id: compress-sbom
        shell: bash
        run: |
          mkdir -p "${{ steps.download-sbom.outputs.download-path }}" && cd $_
          for f in *.spdx.json; do
            gzip -9 "$f"
          done

      - name: Prepare Release
        id: prepare-release
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
          VERSION: ${{ inputs.version }}
          LATEST_IMAGE_REF: ${{ inputs.latest-image-ref }}
        shell: bash
        run: |
          echo "Automated release for ${IMAGE_NAME} version \`${VERSION}\`." > ./changelog.md

          for changelog in ${{ steps.download-changelogs.outputs.download-path }}/*.txt; do
            cat $changelog >> ./changelog.md
          done

          cat <<EOF >> ./changelog.md
          ## How to rebase

          If you're already using this image, upgrade with the following command:

          \`\`\`bash
          sudo bootc upgrade
          \`\`\`

          To switch to this image from another, type the following command in your terminal:

          \`\`\`bash
          sudo bootc switch ${LATEST_IMAGE_REF}
          \`\`\`
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: "${{ inputs.image-name }} version ${{ inputs.version }}"
          tag_name: ${{ inputs.version }}
          body_path: ./changelog.md
          make_latest: true
          files: "${{ steps.download-sbom.outputs.download-path }}/*.spdx.json.gz"
