name: Create release
on:
  workflow_call:
    inputs:
      image-name:
        description: "The name of the image"
        required: true
        type: string
      version:
        description: "The version of the image"
        required: true
        type: string
      pretty-version:
        description: "The pretty version of the image"
        required: true
        type: string
permissions:
  contents: write

jobs:
  retag-image:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Changelogs
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: changelog-${{ inputs.image-name }}-*
          merge-multiple: true
          path: /tmp/changelogs

      - name: Prepare Release
        id: prepare-release
        shell: bash
        run: |
          echo "Automated release for ${{ inputs.image-name }} version ${{ inputs.version }}" > ./changelog.md

          ls -laR /tmp/changelogs
          for changelog in /tmp/changelogs/*.txt; do
            cat $changelog >> ./changelog.md
          done

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          name: "${{ inputs.image-name }} version ${{ inputs.version }}"
          tag_name: ${{ inputs.version }}
          body_path: ./changelog.md
          make_latest: true
